"""posição do pneu no item da OS

Revision ID: d3f6a9c1e7b2
Revises: c2e91f8a6d45
Create Date: 2026-08-11 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f6a9c1e7b2'
down_revision = 'c2e91f8a6d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_os', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicao_pneu', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_os', schema=None) as batch_op:
        batch_op.drop_column('posicao_pneu')

    # ### end Alembic commands ###
