"""pneu substituído no item da OS

Guarda qual pneu (Módulo 7) foi tirado de "Em uso" quando este item de
troca foi lançado, para que seja possível desfazer isso caso o item
seja removido da OS antes de finalizada.

Revision ID: e4a7c2f8b913
Revises: d3f6a9c1e7b2
Create Date: 2026-08-11 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a7c2f8b913'
down_revision = 'd3f6a9c1e7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_os', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pneu_substituido_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_itens_os_pneu_substituido_id', 'pneus', ['pneu_substituido_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_os', schema=None) as batch_op:
        batch_op.drop_constraint('fk_itens_os_pneu_substituido_id', type_='foreignkey')
        batch_op.drop_column('pneu_substituido_id')

    # ### end Alembic commands ###
