"""anexos e controle de tarefas

Revision ID: 9ea4e7c22413
Revises: 4fb38b1f9382
Create Date: 2026-08-01 11:28:25.567145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea4e7c22413'
down_revision = '4fb38b1f9382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controle_tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarefa', sa.String(length=60), nullable=False),
    sa.Column('ultima_execucao', sa.Date(), nullable=True),
    sa.Column('ultimo_resultado', sa.String(length=300), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tarefa')
    )
    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_mime', sa.String(length=80), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.LargeBinary(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('enviado_por', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('abastecimento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abastecimento_id'], ['abastecimentos.id'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anexos')
    op.drop_table('controle_tarefas')
    # ### end Alembic commands ###
