"""ordens de compra

Revision ID: f3c1f82db64f
Revises: f1c4a9d3b562
Create Date: 2026-08-19 12:48:49.474371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c1f82db64f'
down_revision = 'f1c4a9d3b562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('data_solicitacao', sa.Date(), nullable=True),
    sa.Column('solicitante', sa.String(length=120), nullable=True),
    sa.Column('setor', sa.String(length=60), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('aprovado_por', sa.String(length=120), nullable=True),
    sa.Column('data_aprovacao', sa.Date(), nullable=True),
    sa.Column('motivo_reprovacao', sa.String(length=200), nullable=True),
    sa.Column('comprado_por', sa.String(length=120), nullable=True),
    sa.Column('data_compra', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordens_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordens_compra_data_solicitacao'), ['data_solicitacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_compra_numero'), ['numero'], unique=True)

    op.create_table('itens_ordem_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_compra_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=160), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ordem_compra_id'], ['ordens_compra.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_uniforme', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_uniforme_codigo'), ['codigo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_uniforme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_uniforme_codigo'))

    op.drop_table('itens_ordem_compra')
    with op.batch_alter_table('ordens_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordens_compra_numero'))
        batch_op.drop_index(batch_op.f('ix_ordens_compra_data_solicitacao'))

    op.drop_table('ordens_compra')
    # ### end Alembic commands ###
