"""estrutura inicial

Revision ID: 4fb38b1f9382
Revises: 
Create Date: 2026-08-01 03:21:11.824277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb38b1f9382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=60), nullable=True),
    sa.Column('contato', sa.String(length=80), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('momento', sa.DateTime(), nullable=True),
    sa.Column('usuario', sa.String(length=120), nullable=True),
    sa.Column('acao', sa.String(length=20), nullable=True),
    sa.Column('entidade', sa.String(length=60), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('matricula', sa.String(length=30), nullable=True),
    sa.Column('cnh', sa.String(length=20), nullable=True),
    sa.Column('categoria_cnh', sa.String(length=5), nullable=True),
    sa.Column('validade_cnh', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('setor', sa.String(length=60), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefixo', sa.String(length=20), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('modelo', sa.String(length=60), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('combustivel', sa.String(length=30), nullable=True),
    sa.Column('centro_custo', sa.String(length=60), nullable=True),
    sa.Column('setor', sa.String(length=60), nullable=True),
    sa.Column('hodometro', sa.Float(), nullable=True),
    sa.Column('horimetro', sa.Float(), nullable=True),
    sa.Column('situacao', sa.String(length=30), nullable=True),
    sa.Column('km_ultima_troca_oleo', sa.Float(), nullable=True),
    sa.Column('intervalo_troca_oleo', sa.Float(), nullable=True),
    sa.Column('data_ultima_preventiva', sa.Date(), nullable=True),
    sa.Column('intervalo_preventiva_dias', sa.Integer(), nullable=True),
    sa.Column('orcamento_mensal', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veiculos_placa'), ['placa'], unique=True)
        batch_op.create_index(batch_op.f('ix_veiculos_prefixo'), ['prefixo'], unique=True)

    op.create_table('abastecimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('combustivel', sa.String(length=30), nullable=True),
    sa.Column('km_atual', sa.Float(), nullable=True),
    sa.Column('litros', sa.Float(), nullable=True),
    sa.Column('valor_litro', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('tanque_cheio', sa.Boolean(), nullable=True),
    sa.Column('km_percorridos', sa.Float(), nullable=True),
    sa.Column('km_por_litro', sa.Float(), nullable=True),
    sa.Column('custo_por_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abastecimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abastecimentos_data'), ['data'], unique=False)

    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('centro_custo', sa.String(length=60), nullable=True),
    sa.Column('meta_valor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('data_fechamento', sa.Date(), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('mecanico', sa.String(length=80), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('grupo', sa.String(length=40), nullable=True),
    sa.Column('km_veiculo', sa.Float(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('custo_mao_obra', sa.Float(), nullable=True),
    sa.Column('custo_servicos', sa.Float(), nullable=True),
    sa.Column('avaliacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordens_servico_numero'), ['numero'], unique=True)

    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=160), nullable=False),
    sa.Column('grupo', sa.String(length=40), nullable=True),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('estoque_minimo', sa.Float(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('localizacao', sa.String(length=40), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pecas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pecas_codigo'), ['codigo'], unique=True)

    op.create_table('pneus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_fogo', sa.String(length=30), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('posicao', sa.String(length=40), nullable=True),
    sa.Column('marca', sa.String(length=40), nullable=True),
    sa.Column('medida', sa.String(length=30), nullable=True),
    sa.Column('sulco_mm', sa.Float(), nullable=True),
    sa.Column('vida', sa.String(length=20), nullable=True),
    sa.Column('km_instalacao', sa.Float(), nullable=True),
    sa.Column('data_instalacao', sa.Date(), nullable=True),
    sa.Column('data_medicao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_fogo')
    )
    op.create_table('itens_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=160), nullable=True),
    sa.Column('grupo', sa.String(length=40), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('baixado_estoque', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('documento', sa.String(length=60), nullable=True),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentos_estoque')
    op.drop_table('itens_os')
    op.drop_table('pneus')
    with op.batch_alter_table('pecas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pecas_codigo'))

    op.drop_table('pecas')
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordens_servico_numero'))

    op.drop_table('ordens_servico')
    op.drop_table('orcamentos')
    with op.batch_alter_table('abastecimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abastecimentos_data'))

    op.drop_table('abastecimentos')
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculos_prefixo'))
        batch_op.drop_index(batch_op.f('ix_veiculos_placa'))

    op.drop_table('veiculos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('motoristas')
    op.drop_table('logs')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
