"""adiciona token de reset de senha

Revision ID: 8d1cc15d1bb5
Revises: 9ea4e7c22413
Create Date: 2026-08-08 20:41:46.998666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1cc15d1bb5'
down_revision = '9ea4e7c22413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_reset', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('token_reset_expira', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_token_reset'), ['token_reset'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_token_reset'))
        batch_op.drop_column('token_reset_expira')
        batch_op.drop_column('token_reset')

    # ### end Alembic commands ###
